package com.hosteldekho.service;
import com.hosteldekho.dto.ApiDtos.*; import com.hosteldekho.entity.*; import com.hosteldekho.entity.Enums.*; import com.hosteldekho.exception.ApiException; import com.hosteldekho.repository.*; import jakarta.transaction.Transactional; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import java.math.*; import java.util.*; import java.util.stream.*;
@Service @Transactional public class HostelService { final HostelRepository hostels; final CollegeRepository colleges; final ManagerRepository managers; final RoomRepository rooms; final BookingRequestRepository bookings; final MessMenuItemRepository menus; public HostelService(HostelRepository h,CollegeRepository c,ManagerRepository m,RoomRepository r,BookingRequestRepository b,MessMenuItemRepository menu){hostels=h;colleges=c;managers=m;rooms=r;bookings=b;menus=menu;}
 public List<CollegeDto> colleges(){return colleges.findAll().stream().map(c->new CollegeDto(c.getId(),c.getName(),c.getLocality(),c.getCity(),c.getLatitude(),c.getLongitude(),c.getSlug())).toList();}
 public CollegePageDto college(String slug){College c=colleges.findBySlug(slug).orElseThrow(()->notFound("College"));List<Hostel> linked=hostels.findAll().stream().filter(h->h.getCollegeLinks().stream().anyMatch(x->x.getCollege().getId().equals(c.getId()))).toList();List<BigDecimal> prices=linked.stream().flatMap(h->h.getRooms().stream()).map(Room::getPricePerMonth).filter(Objects::nonNull).toList();return new CollegePageDto(c.getId(),c.getName(),c.getSlug(),c.getLocality(),c.getCity(),c.getLatitude(),c.getLongitude(),linked.size(),linked.stream().flatMap(h->h.getRooms().stream()).mapToLong(Room::getVacantBeds).sum(),prices.stream().min(BigDecimal::compareTo).orElse(null),prices.isEmpty()?null:prices.stream().reduce(BigDecimal.ZERO,BigDecimal::add).divide(BigDecimal.valueOf(prices.size()),2,RoundingMode.HALF_UP));}
 public List<HostelCardDto> search(Long collegeId,AcType ac,GenderType gender,Boolean coLiving,BigDecimal min,BigDecimal max,boolean onlyVacant,String locality,Boolean foodIncluded,FoodType foodType){
  return hostels.findAll().stream()
   .filter(h->collegeId==null||h.getCollegeLinks().stream().anyMatch(x->x.getCollege().getId().equals(collegeId)))
   .filter(h->gender==null||h.getGenderType()==gender)
   .filter(h->coLiving==null||h.isCoLiving()==coLiving)
   .filter(h->foodIncluded==null||Objects.equals(h.getMessIncludedInRent(),foodIncluded))
   .filter(h->foodType==null||h.getFoodType()==foodType)
   .filter(h->locality==null||locality.isBlank()||h.getLocality().toLowerCase(Locale.ROOT).contains(locality.toLowerCase(Locale.ROOT)))
   .filter(h->{
    List<Room> matching=h.getRooms().stream().filter(r->ac==null||r.getAcType()==ac)
      .filter(r->min==null||r.getPricePerMonth().compareTo(min)>=0)
      .filter(r->max==null||r.getPricePerMonth().compareTo(max)<=0).toList();
    return !matching.isEmpty()&&(!onlyVacant||matching.stream().anyMatch(r->r.getVacantBeds()>0));
   }).map(h->card(h,collegeId)).toList();
 }
 public HostelDetailDto detail(Long id){return detailOf(hostels.findById(id).orElseThrow(()->notFound("Hostel")));}
 public List<HostelDetailDto> mine(String email){return hostels.findByManagerId(manager(email).getId()).stream().map(this::detailOf).toList();}
 public HostelDetailDto create(String email,HostelRequest r){Hostel h=hostels.save(Hostel.builder().name(r.name()).manager(manager(email)).build());copy(h,r);return detailOf(hostels.save(h));}
 public HostelDetailDto update(String email,Long id,HostelRequest r){Hostel h=owned(email,id);copy(h,r);return detailOf(hostels.save(h));}
 public void delete(String email,Long id){Hostel hostel=owned(email,id);menus.deleteByHostelId(hostel.getId());menus.flush();hostels.delete(hostel);}
 private void copy(Hostel h,HostelRequest r){
  h.setName(r.name());h.setDescription(r.description());h.setAddress(r.address());h.setLocality(r.locality());h.setCity(r.city());h.setLatitude(r.latitude());h.setLongitude(r.longitude());h.setGenderType(r.genderType());h.setCoLiving(r.coLiving());h.setContactName(r.contactName());h.setContactPhone(r.contactPhone());if(r.contactWhatsapp()!=null)h.setContactWhatsapp(normalizeWhatsapp(r.contactWhatsapp()));h.setContactEmail(r.contactEmail());h.setRules(r.rules());h.setAmenities(r.amenities()==null?"":r.amenities());h.setImageUrls(Optional.ofNullable(r.imageUrls()).orElse(List.of()));
  h.setSecurityDeposit(r.securityDeposit());h.setMaintenanceChargePerMonth(r.maintenanceChargePerMonth());h.setMessChargePerMonth(r.messChargePerMonth());h.setElectricityPolicy(r.electricityPolicy());h.setElectricityChargePerMonth(r.electricityChargePerMonth());h.setLockInMonths(r.lockInMonths());h.setNoticePeriodDays(r.noticePeriodDays());h.setMessIncludedInRent(r.messIncludedInRent());h.setFoodType(r.foodType());h.setMealTimings(r.mealTimings());
  List<MessMenuItemDto> menu=Optional.ofNullable(r.weeklyMenu()).orElse(List.of());if(menu.size()>7||menu.stream().anyMatch(x->x.dayOfWeek()==null)||menu.stream().map(MessMenuItemDto::dayOfWeek).distinct().count()!=menu.size())throw new ApiException(HttpStatus.BAD_REQUEST,"Weekly menu allows at most one row per day");menus.deleteByHostelId(h.getId());menus.flush();for(MessMenuItemDto item:menu)menus.save(MessMenuItem.builder().hostel(h).dayOfWeek(item.dayOfWeek()).breakfast(item.breakfast()).lunch(item.lunch()).snacks(item.snacks()).dinner(item.dinner()).build());
  h.getCollegeLinks().clear();hostels.flush();for(CollegeLinkDto l:Optional.ofNullable(r.colleges()).orElse(List.of())){College c=colleges.findById(l.collegeId()).orElseThrow(()->notFound("College"));h.getCollegeLinks().add(HostelCollege.builder().hostel(h).college(c).distanceKm(l.distanceKm()).build());}
 }
 private String normalizeWhatsapp(String number){if(number==null||number.isBlank())return null;String digits=number.replaceAll("\\D","");return digits.length()==10?"91"+digits:digits;}
 public RoomDto addRoom(String email,Long hostelId,RoomRequest r){Hostel h=owned(email,hostelId);return roomDto(rooms.save(room(h,r)));} public RoomDto updateRoom(String email,Long hostelId,Long roomId,RoomRequest r){Room x=rooms.findById(roomId).orElseThrow(()->notFound("Room"));if(!x.getHostel().getId().equals(hostelId))throw new ApiException(HttpStatus.BAD_REQUEST,"Room does not belong to this hostel");owned(email,hostelId);if(r.occupied()>r.capacity())throw new ApiException(HttpStatus.BAD_REQUEST,"Occupied beds cannot exceed capacity");boolean availabilityChanged=x.getOccupied()!=r.occupied()||x.getCapacity()!=r.capacity();x.setRoomNumber(r.roomNumber());x.setAcType(r.acType());x.setCapacity(r.capacity());x.setOccupied(r.occupied());if(availabilityChanged)x.setAvailabilityUpdatedAt(java.time.Instant.now());x.setPricePerMonth(r.pricePerMonth());x.setPricePerDay(r.pricePerDay());x.setDescription(r.description());x.setAmenities(r.amenities());x.setImageUrls(new ArrayList<>(Optional.ofNullable(r.imageUrls()).orElse(List.of())));return roomDto(x);} public void deleteRoom(String email,Long hostelId,Long roomId){Room x=rooms.findById(roomId).orElseThrow(()->notFound("Room"));if(!x.getHostel().getId().equals(hostelId))throw new ApiException(HttpStatus.BAD_REQUEST,"Room does not belong to this hostel");owned(email,hostelId);rooms.delete(x);} private Room room(Hostel h,RoomRequest r){if(r.occupied()>r.capacity())throw new ApiException(HttpStatus.BAD_REQUEST,"Occupied beds cannot exceed capacity");return Room.builder().hostel(h).roomNumber(r.roomNumber()).acType(r.acType()).capacity(r.capacity()).occupied(r.occupied()).availabilityUpdatedAt(java.time.Instant.now()).pricePerMonth(r.pricePerMonth()).pricePerDay(r.pricePerDay()).description(r.description()).amenities(r.amenities()).imageUrls(new ArrayList<>(Optional.ofNullable(r.imageUrls()).orElse(List.of()))).build();}
 public RoomDto changeOccupancy(String email,Long roomId,Integer delta){if(delta==null||(delta!=1&&delta!=-1))throw new ApiException(HttpStatus.BAD_REQUEST,"Delta must be 1 or -1");Room r=rooms.findByIdForUpdate(roomId).orElseThrow(()->notFound("Room"));owned(email,r.getHostel().getId());int next=r.getOccupied()+delta;if(next<0||next>r.getCapacity())throw new ApiException(HttpStatus.CONFLICT,"Occupancy must remain between zero and room capacity");r.setOccupied(next);r.setAvailabilityUpdatedAt(java.time.Instant.now());return roomDto(r);}
 public void confirmAvailability(String email,Long hostelId){Hostel h=owned(email,hostelId);java.time.Instant now=java.time.Instant.now();List<Room> hostelRooms=rooms.findByHostelId(h.getId());hostelRooms.forEach(r->r.setAvailabilityUpdatedAt(now));rooms.saveAll(hostelRooms);}
 public void request(Long roomId,BookingCreateRequest r){Room room=rooms.findByIdForUpdate(roomId).orElseThrow(()->notFound("Room"));if(room.getOccupied()<0||room.getOccupied()>room.getCapacity())throw new ApiException(HttpStatus.CONFLICT,"Room availability is invalid");if(room.getVacantBeds()<1)throw new ApiException(HttpStatus.CONFLICT,"This room is full");bookings.save(BookingRequest.builder().room(room).studentName(r.studentName()).phone(r.phone()).email(r.email()).moveInDate(r.moveInDate()).build());} public List<BookingDto> requests(String email){return bookings.findForManager(manager(email).getId()).stream().map(this::bookingDto).toList();} public BookingDto change(String email,Long id,BookingStatus status){BookingRequest b=bookings.findByIdForUpdate(id).orElseThrow(()->notFound("Booking request"));owned(email,b.getRoom().getHostel().getId());if(b.getStatus()!=BookingStatus.PENDING)throw new ApiException(HttpStatus.CONFLICT,"Request has already been processed");if(status==BookingStatus.APPROVED){Room r=rooms.findByIdForUpdate(b.getRoom().getId()).orElseThrow(()->notFound("Room"));if(r.getOccupied()<0||r.getOccupied()>=r.getCapacity())throw new ApiException(HttpStatus.CONFLICT,"Room is already full");r.setOccupied(r.getOccupied()+1);r.setAvailabilityUpdatedAt(java.time.Instant.now());}b.setStatus(status);return bookingDto(b);}
 private Manager manager(String email){return managers.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Manager not found"));} private Hostel owned(String email,Long id){Hostel h=hostels.findById(id).orElseThrow(()->notFound("Hostel"));if(!h.getManager().getId().equals(manager(email).getId()))throw new ApiException(HttpStatus.FORBIDDEN,"You do not own this hostel");return h;} private ApiException notFound(String n){return new ApiException(HttpStatus.NOT_FOUND,n+" not found");}
 private HostelCardDto card(Hostel h,Long collegeId){List<Room> rs=h.getRooms();BigDecimal price=rs.stream().map(Room::getPricePerMonth).min(BigDecimal::compareTo).orElse(BigDecimal.ZERO);Double distance=collegeId==null?null:h.getCollegeLinks().stream().filter(x->x.getCollege().getId().equals(collegeId)).findFirst().map(HostelCollege::getDistanceKm).orElse(null);return new HostelCardDto(h.getId(),h.getName(),h.getLocality(),h.getGenderType(),h.isCoLiving(),price,rs.stream().mapToInt(Room::getVacantBeds).sum(),distance,tags(h.getAmenities()),List.copyOf(h.getImageUrls()),rs.stream().map(Room::getAcType).distinct().toList());}
 private HostelDetailDto detailOf(Hostel h){List<MessMenuItemDto> weekly=menus.findByHostelIdOrderByDayOfWeek(h.getId()).stream().map(x->new MessMenuItemDto(x.getDayOfWeek(),x.getBreakfast(),x.getLunch(),x.getSnacks(),x.getDinner())).toList();return new HostelDetailDto(h.getId(),h.getName(),h.getDescription(),h.getAddress(),h.getLocality(),h.getCity(),h.getLatitude(),h.getLongitude(),h.getGenderType(),h.isCoLiving(),h.getContactName(),h.getContactPhone(),publicContactEmail(h),h.getRules(),tags(h.getAmenities()),List.copyOf(h.getImageUrls()),h.getCollegeLinks().stream().map(x->new CollegeLinkDto(x.getCollege().getId(),x.getDistanceKm())).toList(),h.getRooms().stream().map(this::roomDto).toList(),h.getSecurityDeposit(),h.getMaintenanceChargePerMonth(),h.getMessChargePerMonth(),h.getElectricityPolicy(),h.getElectricityChargePerMonth(),h.getLockInMonths(),h.getNoticePeriodDays(),h.getMessIncludedInRent(),h.getFoodType(),h.getMealTimings(),weekly,h.getContactWhatsapp());}
 private String publicContactEmail(Hostel h){return h.getManager()!=null&&Objects.equals(h.getContactEmail(),h.getManager().getEmail())?null:h.getContactEmail();}
 private RoomDto roomDto(Room r){CostResult cost=cost(r);return new RoomDto(r.getId(),r.getRoomNumber(),r.getAcType(),r.getCapacity(),r.getOccupied(),r.getVacantBeds(),r.getPricePerMonth(),r.getPricePerDay(),r.getDescription(),r.getAmenities(),List.copyOf(r.getImageUrls()==null?List.of():r.getImageUrls()),cost.complete?cost.total:null,cost.lines,cost.complete,r.getAvailabilityUpdatedAt());}
 private record CostResult(BigDecimal total,List<CostLineDto> lines,boolean complete){}
 private CostResult cost(Room room){Hostel h=room.getHostel();List<CostLineDto> lines=new ArrayList<>();boolean complete=true;BigDecimal total=BigDecimal.ZERO;if(room.getPricePerMonth()!=null){lines.add(new CostLineDto("Monthly rent",room.getPricePerMonth()));total=total.add(room.getPricePerMonth());}else complete=false;if(h.getSecurityDeposit()!=null){lines.add(new CostLineDto("Security deposit",h.getSecurityDeposit()));total=total.add(h.getSecurityDeposit());}else complete=false;if(h.getMaintenanceChargePerMonth()!=null){lines.add(new CostLineDto("Monthly maintenance",h.getMaintenanceChargePerMonth()));total=total.add(h.getMaintenanceChargePerMonth());}else complete=false;if(Boolean.FALSE.equals(h.getMessIncludedInRent())){if(h.getMessChargePerMonth()!=null){lines.add(new CostLineDto("Monthly mess",h.getMessChargePerMonth()));total=total.add(h.getMessChargePerMonth());}else complete=false;}else if(h.getMessIncludedInRent()==null)complete=false;if(h.getElectricityPolicy()==ElectricityPolicy.FIXED){if(h.getElectricityChargePerMonth()!=null){lines.add(new CostLineDto("Fixed electricity charge",h.getElectricityChargePerMonth()));total=total.add(h.getElectricityChargePerMonth());}else complete=false;}else if(h.getElectricityPolicy()==null||h.getElectricityPolicy()==ElectricityPolicy.METERED)complete=false;return new CostResult(total,lines,complete);}
 private BookingDto bookingDto(BookingRequest b){Room r=b.getRoom();return new BookingDto(b.getId(),r.getId(),r.getHostel().getName(),r.getRoomNumber(),b.getStudentName(),b.getPhone(),b.getEmail(),b.getMoveInDate(),b.getStatus(),b.getCreatedAt());}
 private List<String> tags(String s){return s==null||s.isBlank()?List.of():Arrays.stream(s.split(",")).map(String::trim).filter(x->!x.isBlank()).toList();} }
