spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.org.hibernate.SQL=OFF
spring.mvc.log-request-details=false
spring.h2.console.enabled=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
app.jwt.secret=${JWT_SECRET}
app.cors.allowed-origins=${CORS_ORIGINS}
server.port=${PORT:8080}
